# Generated by Django 4.2.4 on 2023-08-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectcandidatejob',
            name='job',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost'),
        ),
    ]
